Traceback (most recent call last):
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pooch
POOCH = pooch.create(
    path=pooch.os_cache("noaa-data"),
    base_url="doi:10.5281/zenodo.5564850/",
    registry={
        "data.txt": "md5:5129dcfd19300eb8d4d8d1673fcfbcb4",
    },
)
datafile = POOCH.fetch("data.txt")
datafile
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [40][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpooch[39;00m
[1;32m      2[0m POOCH [38;5;241m=[39m pooch[38;5;241m.[39mcreate(
[1;32m      3[0m     path[38;5;241m=[39mpooch[38;5;241m.[39mos_cache([38;5;124m"[39m[38;5;124mnoaa-data[39m[38;5;124m"[39m),
[1;32m      4[0m     base_url[38;5;241m=[39m[38;5;124m"[39m[38;5;124mdoi:10.5281/zenodo.5564850/[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m      7[0m     },
[1;32m      8[0m )
[1;32m      9[0m datafile [38;5;241m=[39m POOCH[38;5;241m.[39mfetch([38;5;124m"[39m[38;5;124mdata.txt[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'pooch'
ModuleNotFoundError: No module named 'pooch'

